[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_point_system = "4j7TmiMhCrWctQXoUTiCasiZVK7987b9ia1Hf1CGxSGR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/maarunipandithurai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "anchor build && anchor deploy && anchor run test"
